### PR TITLE
add net assets

### PR DESCRIPTION
**Pull request by cybojenix**

### CODE REVIEW

**Comment by raoulsullivan** [comment]
@cybojenix can you check the fix i just made? the only important one is net_assets -> assets to be consistent with business_assets (which has no 'net' prefix)

**Comment by raoulsullivan** [comment]
Also these are inconsistent now - "business assets" is about "physical business assets", whereas "assets" is about "business assets"

**Comment by cybojenix** [comment]
yeah, this is a pita. We need to make a decision about translations + current data before solving this one

**Comment by nesaro** [comment]
@cybojenix decision made two days ago: to move to sme_v6

**Comment by cybojenix** [comment]
stale

**Pull request closed without merging**
