### PR TITLE
cap on tap mobile number field

### PR DESCRIPTION
**Pull request by tony-truong88**
Added mobile_phone to schema for cap on tap API [ch5532]

### CODE REVIEW

**Comment by jmstaley** [comment]
@tony-truong88 failing tests dude

**Comment by tony-truong88** [comment]
> @tony-truong88 failing tests dude

Yup, fixing now.

**Comment by tony-truong88** [comment]
Yeah, annoying. Looks fine locally.

**Comment by tony-truong88** [comment]
Finally passed. Ready for review 😄

**Pull request merged**
